apiVersion: v1
kind: Service
metadata:
  name: {{ include "nexus-charts.fullname" . }}
  labels:
    {{- include "nexus-charts.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.httpport }}
      targetPort: 8081
      protocol: TCP
      name: http
    - port: {{ .Values.service.dockerport }}
      targetPort: 5000
      protocol: TCP
      name: docker
  selector:
    {{- include "nexus-charts.selectorLabels" . | nindent 4 }}
